2차원 리스트

<img src="./images/2Dim.png" align="left" width="1200"/>

In [1]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [2]:
# 리스트이름 = [[0] * 열개수 for i in range(행개수)]
b = [[0] * 5 for i in range(4)]
print(b)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [3]:
import numpy as np

In [4]:
print(np.array(a))
print(np.array(b))

[[1 2 3]
 [4 5 6]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
print(len(b)) # 행의 개수
print(len(b[0])) # 열의 개수
# print(b.shape) # 에러
print(np.array(a).shape)
print(np.array(b).shape)
print(np.array(b).shape[0])
print(np.array(b).shape[1])

4
5
(2, 3)
(4, 5)
4
5


In [6]:
for i in range(len(b)):
    print(b[i])

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [7]:
for i in range(len(b)):
    for j in range(len(b[i])):
        print(b[i][j], end=' ')
    print()

0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 


<img src="./images/2Dim_Zigzag.png" align="left" width="350"/>

In [8]:
def pprint(data):
    for i in range(len(data)):
        for j in range(len(data[i])):
            print('{:3d}'.format(data[i][j]), end=' ')
        print() 

In [9]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0 # 리스트에 1씩 증가하며 채워질 숫자가 기억되는 변수

for i in range(len(data)): # 행
    # 짝수행은 숫자가 왼쪽에서 오른쪽으로 채워지고 홀수행은 숫자가 오른쪽에서 왼쪽으로 채워진다.
    # 짝수행인가 홀수해인가 판단한다.
    if i % 2 == 0: # 짝수인가?
        # 짝수행은 왼쪽에서 오른쪽으로 숫자를 채운다. j => 0, 1, 2, 3, 4
        for j in range(len(data[i])):
            n += 1
            data[i][j] = n
    else:
        # 홀수행은 오른쪽에서 왼쪽으로 숫자를 채운다. j => 4, 3, 2, 1, 0
        for j in range(len(data[i]) - 1, -1, -1):
            n += 1
            data[i][j] = n

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 5
  1   2   3   4   5 
 10   9   8   7   6 
 11  12  13  14  15 
 20  19  18  17  16 


In [10]:
# i = 0, sw =  1, j = 0, 1, 2, 3, 4 => range(0, 5, sw)
# i = 1, sw = -1, j = 4, 3, 2, 1, 0 => range(4, -1, sw)
# i = 2, sw =  1, j = 0, 1, 2, 3, 4 => range(0, 5, sw)
# i = 3, sw = -1, j = 4, 3, 2, 1, 0 => range(4, -1, sw)
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0
start = 0 # 2차원 리스트에 숫자가 채워지기 시작하는 열 인덱스
end = col - 1 # 2차원 리스트에 숫자가 채워지는 마지막 열 인덱스
# 왼쪽에서 오른쪽으로, 오른쪽에서 왼쪽으로 숫자가 채워지는 방향을 제어하는 변수
sw = 1 # start 부터 end 까지 증가치로 사용할 변수

for i in range(row):
    for j in range(start, end + sw, sw):
        # print(f'[i = {i}, j = {j}]', end='')
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
    sw *= -1
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 5
  1   2   3   4   5 
 10   9   8   7   6 
 11  12  13  14  15 
 20  19  18  17  16 


In [11]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0
start = [i for i in range(col)] # 왼쪽부터 오른쪽으로 진행하는 열 인덱스를 기억하는 리스트
end = [i for i in range(col - 1, -1, -1)] # 오른쪽부터 왼쪽으로 진행하는 열 인덱스를 기억하는 리스트
# print(start, end)

for i in range(row):
    for j in start:
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 5
  1   2   3   4   5 
 10   9   8   7   6 
 11  12  13  14  15 
 20  19  18  17  16 
