In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

numpy 파일 입출력

numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.

In [2]:
# 메소드 이름    기능                                                   파일 포맷
# save()         numpy 배열 객체 1개를 바이너리 파일로 저장한다.        바이너리
# savez()        numpy 배열 객체 여러 개를 바이너리 파일로 저장한다.    바이너리
# load()         numpy 배열 저장 파일로 부터 배열 객체를 읽어온다.      바이너리
# ====================================================================================
# savetxt()      numpy 배열 객체를 텍스트 파일로 저장한다.              텍스트
# loadtxt()      텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.       텍스트

In [3]:
a = np.random.randint(0, 10, (2, 3))
print(a)
b = np.random.randint(0, 10, (2, 3))
print(b)

[[8 9 4]
 [9 0 7]]
[[5 6 4]
 [5 2 1]]


numpy 배열 객체를 바이너리 파일로 저장

In [4]:
# save(), savez() 메소드를 사용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# save(): 배열 1개를 저장한다. 확장명 => npy
# savez(): 배열 여러 개를 저장한다. 확장명 => npz

# a 배열을 바이너리 파일로 저장한다.
# save('경로명', 배열명)
np.save('./output/my_array1', a)

# a, b 배열을 바이너리 파일로 저장한다.
# savez('경로명', 배열명1, 배열명2, ...)
np.savez('./output/my_array2', a, b)

바이너리 파일로 저장된 numpy 배열 객체 읽어오기

In [5]:
# load() 메소드로 npy, npz 파일로 부터 데이터를 읽어올 수 있다.
# npy 파일 읽기
# 저장할 때는 메소드가 달라서 확장명이 다르게 붙기 때문에 파일명만 입력하면 되지만 읽어올 때는 읽어올 때는 메소드가
# 같아서 확장명 까지 입력해야 한다.
# load('경로명')
print(np.load('./output/my_array1.npy'))

[[8 9 4]
 [9 0 7]]


In [6]:
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFile = np.load('./output/my_array2.npz')
print(npzFile['arr_0'])
print(npzFile['arr_1'])

[[8 9 4]
 [9 0 7]]
[[5 6 4]
 [5 2 1]]


numpy 배열 객체를 텍스트 파일로 저장

In [7]:
c = np.random.random((3, 4))
print(c)

[[0.13840551 0.67224962 0.88149834 0.54852469]
 [0.8061852  0.05382414 0.82020966 0.7672822 ]
 [0.70507376 0.36642923 0.1666319  0.83462043]]


In [8]:
# 텍스트 파일은 확장명이 txt인 파일을 의미하는 것이 아니고 확장명이 csv 또는 tsv인 파일을 의미한다.
# savetxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장할 수 있다.
# savetxt('경로명', 배열명, delimiter='구분자')
np.savetxt('./output/saved.csv', c, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved.tsv', c, delimiter='\t') # tsv 파일은 데이터를 tab으로 구분한다.

텍스트 파일로 저장된 numpy 배열 객체 읽어오기

In [9]:
# loadtxt() 메소드로 텍스트 파일로 저장된 numpy 배열 객체를 읽어올 수 있다.
# loadtxt('경로명', dtype, delimiter='구분자')
print(np.loadtxt('./output/saved.csv', dtype=np.float, delimiter=','))
print(np.loadtxt('./output/saved.tsv', dtype=np.int, delimiter='\t'))

[[0.13840551 0.67224962 0.88149834 0.54852469]
 [0.8061852  0.05382414 0.82020966 0.7672822 ]
 [0.70507376 0.36642923 0.1666319  0.83462043]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


배열(행렬) 연산 - 산술 연산

In [10]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [11]:
# 덧셈: +, add()
print(a + b)
print(np.add(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [12]:
# 뺄셈: -, subtract()
print(a - b)
print(np.subtract(a, b))

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [13]:
# 곱셈: *, multiply()
print(a * b)
print(np.multiply(a, b))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [14]:
# 나눗셈: /, divide()
print(a / b)
print(np.divide(a, b))

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [15]:
print(a // b)
print(a % b)

[[0 0 0]
 [0 1 1]
 [2 4 9]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]


In [16]:
# 지수
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [17]:
# 제곱근
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [18]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [19]:
# 로그
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [20]:
# 행렬의 내적
print(np.dot(a, b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<img src="./images/dot.png" align="left" width="800"/>

배열(행렬) 연산 - 비교 연산

In [21]:
# 배열 요소별 비교: >, >=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [22]:
# 배열 전체 비교: array_equal() 메소드
print(np.array_equal(a, b))

False


집계 함수

numpy의 모든 집계 함수는 axis를 기준으로 게산하며 집계 함수에 axis를 지정하지 않으면 None이 기본값으로 사용된다.

In [23]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]


합계: 넘파이배열.sum(), np.sum(넘파이배열)

In [24]:
# axis=None
# axis=None은 전체 배열을 행과 열을 구분하지 않고 전체 합계를 계산한다. 생략시 기본값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


<img src="./images/numpyImage02.jpg" align="left" width="200"/>

In [25]:
# axis=0
# axis=0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 계산한다. => 각 열의 합계
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


<img src="./images/numpyImage03.jpg" align="left" width="200"/>

In [26]:
# axis=1
# axis=1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 계산한다. => 각 행의 합계
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


<img src="./images/numpyImage04.jpg" align="left" width="200"/>

최대값: 넘파이배열.max(), np.max(넘파이배열), 최소값: 넘파이배열.min(), np.min(넘파이배열)

In [27]:
print(a.max()) # print(a.max(axis=None))
print(np.max(a)) # print(np.max(a, axis=None))
print(a.min()) # print(a.min(axis=None))
print(np.min(a)) # print(np.min(a, axis=None))

9
9
1
1


In [28]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=0))
print(np.min(a, axis=0))

[7 8 9]
[7 8 9]
[1 2 3]
[1 2 3]


In [29]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1))
print(np.min(a, axis=1))

[3 6 9]
[3 6 9]
[1 4 7]
[1 4 7]


누적 합계: 넘파이배열.cumsum(), np.cumsum(넘파이배열)

In [30]:
print(a.cumsum()) # print(a.cumsum(axis=None))
print(np.cumsum(a)) # print(np.cumsum(a, axis=None))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [31]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [32]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균: 넘파이배열.mean(), np.mean(넘파이배열)

In [33]:
print(a.mean()) # print(a.mean(axis=None))
print(np.mean(a)) # print(np.mean(a, axis=None))

5.0
5.0


In [34]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

[4. 5. 6.]
[4. 5. 6.]


In [35]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

[2. 5. 8.]
[2. 5. 8.]


중위수: np.median(넘파이배열)

In [36]:
print(np.median(a)) # print(np.mean(a, axis=None))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


상관계수: np.corrcoef(넘파이배열)

In [37]:
print(np.corrcoef(a)) # axis를 사용하지 않는다.

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


표준편차: 넘파이배열.std(), np.std(넘파이배열)

In [38]:
print(a.std()) # print(a.std(axis=None))
print(np.std(a)) # print(np.std(a, axis=None))

2.581988897471611
2.581988897471611


In [39]:
print(a.std(axis=0))
print(np.std(a, axis=0))

[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]


In [40]:
print(a.std(axis=1))
print(np.std(a, axis=1))

[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]


브로드캐스팅

shape이 같은 두 배열에 대한 이항 연산은 배열 요소별로 실행된다.  
두 배열의 shape이 다를 경우 두 배열 간의 형상(모양)을 맞추는 그림과 같은 브로드캐스팅 과정을 거쳐서 실행된다.

<img src="./images/numpyImage05.jpg" align="left" width="900"/>

shape이 같은 두 배열의 연산

In [41]:
a = np.arange(1, 25).reshape(4, 6)
pprint(a)
b = np.arange(25, 49).reshape(4, 6)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [42]:
# shape이 같은 배열을 이항 연산할 경우 위치가 같은 요소 단위로 실행된다.
print(a + b)

[[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


shape이 다른 두 배열의 연산

shape이 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생 시 두 배열을 같은 shape으로 만든 후 연산을 실행한다.

In [43]:
# 배열과 스칼라(단일 값)의 연산
# 배열과 스칼라 사이의 이항 연산 시 스칼라를 배열로 변환한다.
a = np.arange(1, 25).reshape(4, 6)
print(a)
print(a + 100)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [44]:
# a + 100은 다음과 같은 과정을 거쳐서 처리된다.
new_arr = np.full_like(a, 100)
print(new_arr)
print(a + new_arr)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [45]:
# shape이 다른 배열의 연산
a = np.arange(5).reshape(1, 5)
print(a)
b = np.arange(5).reshape(5, 1)
print(b)
print(a + b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


벡터 연산

numpy는 벡터 연산을 지원한다.  
numpy 집합 연산에는 벡터화 기능이 적용되어 있어서 벡터 처리에 대해 벡터 연산을 적용할 경우 처리 속도가 100배 이상 빠르다.

In [46]:
a = np.arange(10000000, dtype=np.int64)

In [47]:
%%time
result = 0
for i in a:
    result += i
print(result)

49999995000000
Wall time: 2.49 s


In [48]:
%%time
result = np.sum(a)
print(result)

49999995000000
Wall time: 17 ms


배열 복사

ndarray 배열 객체에 대핸 인덱싱, 슬라이싱이 반환하는 배열은 새로운 객체가 아닌 기존 배열의 view이다.  
반환된 배열의 값을 변경하면 원본 배열에 변경한 값이 반영된다. - 앝은 복사

In [49]:
a = np.random.randint(0, 9, (3, 3))
print(a)
print(a[:, 0]) # 행은 상관없이 0번째 열만 슬라이싱 한다.
a[:, 0] = 999
print(a[:, 0])
print(a)

[[1 4 3]
 [1 2 5]
 [5 4 3]]
[1 1 5]
[999 999 999]
[[999   4   3]
 [999   2   5]
 [999   4   3]]


기존 배열로 부터 새로운 배열을 생성하기 위해 copy() 메소드를 사용한다.  
copy() 메소드로 복사된 배열은 원본 배열과 완전히 다른 별도의 객체가 된다. - 깊은 복사

넘파이배열.copy(), np.copy(넘파이배열)

In [50]:
a = np.random.randint(0, 9, (3, 3))
print(a)
copied_a = np.copy(a)
print(copied_a)
copied_a[:, 0] = 777
print(copied_a)
print(a)

[[1 2 5]
 [5 5 4]
 [1 3 6]]
[[1 2 5]
 [5 5 4]
 [1 3 6]]
[[777   2   5]
 [777   5   4]
 [777   3   6]]
[[1 2 5]
 [5 5 4]
 [1 3 6]]


배열 정렬

ndarray 객체는 axis를 기준으로 요소를 정렬하는 sort() 메소드를 제공한다.

In [51]:
unsorted_arr = np.random.random((3, 3))
print(unsorted_arr)

[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]


In [52]:
# 정렬 작업을 위해 복사본을 만든다.
unsorted_arr1 = unsorted_arr.copy()
print(unsorted_arr1)
unsorted_arr2 = unsorted_arr.copy()
print(unsorted_arr2)
unsorted_arr3 = unsorted_arr.copy()
print(unsorted_arr3)

[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]
[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]
[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]


넘파이배열.sort(): 정렬을 실행한 결과가 넘파이 배열에 바로 반영된다.  
sort() 메소드의 axis 기본값은 None이 아니고 -1이다.  
-1은 현재 배열의 마지막 axis를 의미하고 unsorted_arr는 2차원이므로 axis가 0, 1이 존재하고 이 때 마지막 axis는 1이다.

In [53]:
unsorted_arr1.sort()
print(unsorted_arr1)
unsorted_arr2.sort(axis=-1)
print(unsorted_arr2)
unsorted_arr3.sort(axis=1)
print(unsorted_arr3)

[[0.0697513  0.42918914 0.70512202]
 [0.12067861 0.52209075 0.69588192]
 [0.110527   0.11309726 0.60279832]]
[[0.0697513  0.42918914 0.70512202]
 [0.12067861 0.52209075 0.69588192]
 [0.110527   0.11309726 0.60279832]]
[[0.0697513  0.42918914 0.70512202]
 [0.12067861 0.52209075 0.69588192]
 [0.110527   0.11309726 0.60279832]]


In [54]:
unsorted_arr4 = unsorted_arr.copy()
print(unsorted_arr4)

[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]


np.sort(넘파이배열): 정렬을 실행한 결과를 리턴한다.

In [57]:
a = np.sort(unsorted_arr4, axis=0)
print(unsorted_arr4)
print(a)

[[0.42918914 0.70512202 0.0697513 ]
 [0.12067861 0.52209075 0.69588192]
 [0.11309726 0.110527   0.60279832]]
[[0.11309726 0.110527   0.0697513 ]
 [0.12067861 0.52209075 0.60279832]
 [0.42918914 0.70512202 0.69588192]]


In [59]:
b = np.sort(unsorted_arr4, axis=0)[::-1] # 내림차순 정렬
print(b)

[[0.42918914 0.70512202 0.69588192]
 [0.12067861 0.52209075 0.60279832]
 [0.11309726 0.110527   0.0697513 ]]
